// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl0vtpTKG0PJCQyOq_c3XZ-TqvKXong70',
    appId: '1:73189345761:web:b56f9e0bd2b06facaa6aa0',
    messagingSenderId: '73189345761',
    projectId: 'ougikawaii',
    authDomain: 'ougikawaii.firebaseapp.com',
    storageBucket: 'ougikawaii.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMsgTsS5icmNDDRF5dmLkKawbFd3yiee4',
    appId: '1:73189345761:android:9537c15563a5527faa6aa0',
    messagingSenderId: '73189345761',
    projectId: 'ougikawaii',
    storageBucket: 'ougikawaii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBntwRWlV45OUsaJ4GqLaxr8isAYZSUj6Y',
    appId: '1:73189345761:ios:9c6e62ee15b2b7adaa6aa0',
    messagingSenderId: '73189345761',
    projectId: 'ougikawaii',
    storageBucket: 'ougikawaii.appspot.com',
    iosClientId: '73189345761-0si2ck0pcd1ds8btk9g9kf59emiciup1.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBntwRWlV45OUsaJ4GqLaxr8isAYZSUj6Y',
    appId: '1:73189345761:ios:4d410cb94a6aaf50aa6aa0',
    messagingSenderId: '73189345761',
    projectId: 'ougikawaii',
    storageBucket: 'ougikawaii.appspot.com',
    iosClientId: '73189345761-elu233nh6pltgaj8qjos69hcujg039eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled7.RunnerTests',
  );
}
